/*
This program has been developed by students from the bachelor Computer Science at
Utrecht University within the Software Project course.
© Copyright Utrecht University (Department of Information and Computing Sciences)
 */

/**
 * This module contains a function that handles the creation of the HTML file. It compiles the EJS files into
 * an HTML file, and inserts the data generated by the program.
 *
 * @module
 */

import * as fs from "fs";
import { ReturnObject } from "./getdata";
import ejs from "ejs";
import path from "path";

/**
 * Creates a webapp that reports the data gathered by FAIRSECO.
 *
 * @param data The gathered data.
 * @param filePath The path to which the HTML file will be written.
 */
export async function WriteHTML(
    data: ReturnObject[],
    filePath: string = "./.FAIRSECO/",
    templatePath: string = "./FAIRSECO_Assets/templates/"
): Promise<void> {
    const template = await ejs.renderFile(
        path.join(templatePath, "index.ejs"),
        { data }
    );
    const template2 = await ejs.renderFile(
        path.join(templatePath, "citationgraph.ejs"),
        { data }
    );
    await fs.promises.writeFile(
        path.join(filePath, "dashboard.html"),
        template,
        "utf8"
    );
    await fs.promises.writeFile(
        path.join(filePath, "citationgraph.html"),
        template2,
        "utf8"
    );
}
